spring.datasource.url=jdbc:mysql://localhost:3306/educhat_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=WJ28@saidr
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8080
google.ai.api.key=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